### ISSUE TITLE
Update to Heroicons 2? (blade-heroicons v2)

### ISSUE THREAD

**Issue by vmitchell85** [stefangalescu/statamic-heroicons#1]
Do you plan to update to heroicons 2? Should just be a composer require change, and tag a new release...

Thanks for considering.

**Comment by stefangalescu** [comment]
Yes, I'll look into it over the next days

**Comment by pdipatrizio** [comment]
Any update @stefangalescu ?

**Comment by stefangalescu** [comment]
I've released a new major version to support Heroicons v2. Please check out the release notes as there are some breaking changes. Sorry it took so long to get it out! Do let me know if any issues arise.
