### ISSUE TITLE
If Icon Doesn't Exist, Return Nothing Instead of Breaking Page

### ISSUE THREAD

**Issue by mc4rdle** [stefangalescu/statamic-heroicons#4]
I'm using a text field for my clients to add the icon name. Sometimes they type an icon name that doesn't exist or they misspell it and it breaks the entire page. Could the plugin just not try to render the icon if there's an error rather than break the entire page.

https://prnt.sc/EdHCaUnUXZVG

**Comment by stefangalescu** [comment]
That makes sense. Would it also help if it would report the exception while continuing the code execution?

**Comment by mc4rdle** [comment]
Not that important to me personally, I just don't want the clients to mistype the icon name and break the site.
